### ISSUE TITLE
Support for new A2M file versions?

### ISSUE THREAD

**Issue by tomas** [adplug/adplug#14] opened 2016-04-01 07:45 UTC
Hello developers of the glorious adplug.

I was wondering if you have any plans to support the newer versions of the [A2M format](http://adlibtracker.net/files/techinfo.htm#_Toc389385056), namely 9, 10 and 11. As it is, some of the songs distributed in the AT2 package are currently unplayable by adplug.

I'd be happy to help out with testing, if needed.

**Comment by Malvineous** [comment] 2016-04-01 11:33
No plans at the moment, but we're more than happy to take patches if you can convince someone to work on it!

**Comment by illydan** [comment] 2016-04-01 13:15
It's also far from easy as Adlib Tracker 2 is written in Pascal while Adplug uses C++.
It would be easier to recode the function you need from adplug (command line player?).
(I've created the adt2plug winamp plugin because of that)

**Comment by tomas** [comment] 2016-04-01 16:33
@Malvineous I see. No chance of convincing you, eh? :)

@illydan I'm not sure what you mean. Recode the function from adplug into what? Does your winamp plugin support the new versions of the format?

**Comment by illydan** [comment] 2016-04-01 17:40
I don't want to make any advertising but adt2plug is the "official" winamp plugin of adt2 - so yeah - it supports the newest format as it's based upon the ADT2 source codes - check the adlibtracker2 site for links.
The Problem is that the whole replayer either needs to be converted to C++ or converted to adplug's internal replayer. The new ADT2 versions include a big instrument macro engine which needs a complete C++ conversion of the (not small) Pascal sources.
So it's nothing small - and convincing one to rewrite 14000 lines of Pascal into C++ is - sorry - absurd. 
Linking Pascal to C++ would be a stopgap solution but then would require everyone to include fpc (the freepascal compiler) into their build-chain. 
IMHO not worth it because there is a different plugin made especially for A2M available.
That's also why I've said that it'll be easier to recode the functionality you use from adplug (which i don't know - it could be command line player or winamp plugin etc) into adt2plug rather then doing it the other way around.
I'd suggest to close this bug as WONTFIX

**Comment by tomas** [comment] 2016-04-01 18:16
Closing this issue doesn't help anyone IMHO. As long as Adplug doesn't officially declare they WONT support the newer versions, this issue at least lets everyone be aware and keep track of the situation.

And by the way, I never asked to merge the AT2 pascal sources into adplug's codebase, or to rewrite 14000 lines of code. I just want to be able to play newer AT2 songs using adplug in Linux or OSX.

**Comment by Malvineous** [comment] 2016-04-01 22:13
I'll leave the issue open because it is a limitation in AdPlug, and perhaps someone with some time on their hands might stumble across it and start working on it.  At the very least it'll stop the issue from being logged again and again as other people run into the same problem.

Sounds like it would be a very big job though, so probably not worth holding out too much hope!  Sadly I don't have much time to work on AdPlug myself, so I'm just coordinating patches that other people submit.

Linking to external libraries to reuse that code would be fine, just as long as the build system is set up so that the library is optional.  That way people won't be forced to change their build chain (they'll just miss out on this format) but if they choose to install the external libraries then they'll get an extra format in AdPlug as a result.

**Comment by tomas** [comment] 2016-04-02 19:54
Sounds good. I'm not an expert at C but I'll try to give it a shot. Do you have specific guidelines for code syntax?

**Comment by Malvineous** [comment] 2016-04-02 21:59
Not really - as long as it's neat and readable you should be fine.  There's quite a few different coding styles in there already, so you'd only need to match an existing style if you're editing one of the existing files.  Good luck!

**Comment by tomas** [comment] 2016-04-05 18:17
@Malvineous Just wanted to inform that I'm actually getting somewhere, contrary to even my own expectations. Whenever I'm able to get something working I'll let you know.

**Comment by Malvineous** [comment] 2016-04-05 21:47
Sounds great!  Hope you continue to have success with it.

**Comment by TheEssem** [comment] 2019-07-02 04:51
Any updates on this?

**Comment by tomas** [comment] 2019-07-02 13:53
@TheEssem It's been a while since I last dove into this, but I think I was able to get a basic working version, with a few issues. I tried to get them fixed but couldn't get around them.

If anyone's interested in taking a look at the code I can upload it somewhere.

**Comment by mconfalonieri** [comment] 2019-10-21 12:01
Is the code posted somewhere? I can't promise anything, as I am quite new to AdPlug, that I used it for a player [I am writing](https://github.com/mconfalonieri/sadplay) but I could have a look.

**Comment by tomas** [comment] 2019-10-21 14:43
@mconfalonieri [This is the branch](https://github.com/adplug/adplug/compare/master...tomas:a2m_loader?expand=1) I was working on. It's been a while since I last looked at that code, so I'm not sure which was the part I got stuck. Let us know how it goes!

**Comment by Televicious** [comment] 2021-01-22 08:27
Boy I was hoping someone could tackle this. Needed for the mobile version of adplug to play a2m since winamp doesn't exist on android.

**Comment by tomas** [comment] 2021-01-22 16:38
If no one's currenlty working on this, maybe I can give it another shot.

**Comment by mywave82** [comment] 2021-01-22 17:10
Sounds great

**Comment by dmitrysmagin** [comment] 2023-03-19 18:42
Hi.
I've ported a2m replayer from Pascal to C some time ago:
https://github.com/dmitrysmagin/a2t_play
It supports up to latest v14 tunes, though there are some minor sound differences with the original, can't say if this is because of code errors or smth.
Note that the code is pretty horrible by style because it's a literal hand translation from Pascal. Before it can be included directly into adplug, it needs some refactoring.

**Comment by mywave82** [comment] 2023-03-19 19:46
I am just thinking out here, not making any promises.

Ideal target for adplug is to make each playback plugin register-perfect with the original player/tracker.

To track down the difference in the original code and your player, logging all register writes (including which OPL bank/chip) in the original Pascal version and your C version is the most ideal path to go. Then a simple text diff can be used.

If we are going to replace the engine already in adplug, the code needs to be refactored into self-contained C++ object that fits the adplug model. This is mostly moving global variables into the class.

Keeping to code-structure organized the same way as the original might make future updates easier.

**Comment by dmitrysmagin** [comment] 2023-03-19 20:44
I'd leave the old adplug a2m.c playing engine for files version 1-8 and used the new player for versions 9-14.

**Comment by mywave82** [comment] 2023-04-02 08:53
Regarding packed structs:
In adplug there is libbinio which can be used to read out one and one byte/short/integer, and it can also perform endian swapping so that it works on forreign endian systems.

**Comment by dmitrysmagin** [comment] 2023-04-02 12:18
I think I can make a workaround without using libbinio because a2m implies that all its data is little-endian.
As it turns out, if a struct has only char (uint8_t) members including nested structs/unions/arrays of chars of any levels, there's no padding at all and we can have the necessary size without resorting to compile-specific options. And this is standard bevahviour.
````
struct Struct {
    uint8_t a, b[9], c[11][13];
    struct {
        uint8_t  s, s[3];
    } s1, s2[3]; 
};
````
All above has no hidden padding anywhere.
So, when the player reads (in fact, unpacks) a chunk of data from file into a struct, we can 100% have a predictable result by default.  All non-char values could be safely split into such (uint16_t wordval; => uint8_t wordval_lo; uint8_t wordval_hi).
As said before, all data in a2m is little-endian, we don't have to worry about it.

**Comment by Malvineous** [comment] 2023-04-02 21:58
Fair point, but the purpose of libbinio is to avoid reimplementing all this endian logic in all the replayers, and have one well-tested implementation that we know works everywhere!  So if you're only dealing with `uint8_t` fair enough, but as soon as you are working with `uint16_t` or larger, it'd be better to use libbinio.

It just means you have to read each field individually instead of in a single statement, which isn't a huge problem really.

**Comment by dmitrysmagin** [comment] 2024-01-29 06:52
Hi.
Just wanted to inform that I've resolved all problems with memory and packed structures in https://github.com/dmitrysmagin/a2t_play and now the  code is more or less ready to be moved to adplug.

@mywave82
Some questions:

The code is using multiple unpack algos from various sources:

1. aPLib v0.26b by Joergen Ibsen (http://www.ibsensoftware.com/); it is incompatible with later versions (v.1.1.0 for example)
2. Sixpack by Philip G. Gage (used in existing a2m.cpp in adplug)
3. lzh by Haruhiko Okumura (ar002.rar, can be found here: https://archive.org/details/LDSKitv1.1-2004-12-28) - also with custom tweaks

The question is: would it be more convenient to place the code to separate .c files (depack.c, sixpack.c, unlzh.c) and include them into .cpp and .h accordingly instead of including them into one fat a2m.cpp? I'm not sure about licenses of the unpackers, they seem to be either public domain or freeware.

Question2: better replace the old a2m.cpp player or add v2 one (a2m-v2.cpp) for a2m v9-14 and a2t v1-14 ?

**Comment by Malvineous** [comment] 2024-01-29 08:40
Separate files would be a bit cleaner and open the possibility of reuse so that would be my preference, but perhaps with descriptive names (sixpack is fine but depack is a bit generic).

We'll have to confirm the code is public domain or otherwise compatible with LGPL before including it, or rewrite the algos.

If your new player completely supports the existing files then you can replace the old player, however if you only support newer versions then it would be best to keep the old player around for the older versions (and if needed, update it to reject the newer versions that your player will handle instead).

**Comment by mywave82** [comment] 2024-01-29 09:32
When you add the PR, mention the current status of the license situation of each file.

For instance, LZH stuff there are multiple instances of online, so it can likely be replaced or remade if needed if needed.

**Comment by dmitrysmagin** [comment] 2024-02-26 07:55
https://github.com/adplug/adplug/pull/207

**Closed** 2024-05-31 11:46 UTC
Labels: enhancement, help wanted
