### ISSUE TITLE
User configurable FREQ_OFFSET? 

### ISSUE THREAD

**Issue by PalMusicFan** [adplug/adplug#70] opened 2018-11-01 01:11 UTC
The surroundopl is really a fantastic enhancement of the OPL2 mono music formats. However, as I found in "surroundopl.h", the FREQ_OFFSET of the right channel is not configurable in run-time. Though "128.0" performs well in most of the tracks, we have found some percussion sound effects not compatible with it. Please refer to the DRO clip attached. As we heard, there is a percussion sound effect sounds well in the left channel while there is a distortion in the right channel. 

Although "384.0" solves this problem and the stereo effect is still nice, I have no idea whether this value is universally suitable. So, is it better to make it user configurable?

Thanks so much!  

[pal_percussion.zip](https://github.com/adplug/adplug/files/2536861/pal_percussion.zip)

**Comment by PalMusicFan** [comment] 2018-11-01 02:00
Actually we found this percussion sound effect requires an more accurate OPL frequency.

**Comment by Malvineous** [comment] 2018-11-01 10:10
I'm not sure that it's worth the effort of making it user configurable, however I'm open to accepting patches.  I will try to get some time to listen to the DRO clip as it sounds like the problem is that the frequency transposition isn't working correctly, which means changing the offset will just move the problem note to some other frequency instead.  So better to fix the frequency calculations so the problem goes away entirely.

In my own early experiments, values much below 110 made the effect difficult to notice, and values above 150 started to introduce dissonance making the songs sound off-key, so the actual range of values that sounded good was so small I didn't think it would be useful for end-users to be able to change it.

**Comment by PalMusicFan** [comment] 2018-11-02 01:50
Thanks for your reply! 
The following data is the result of my test I just made: 
182 and below: distortion 
183 to 364: not correct, however similar as a "spring sound"
365 and above: correct 
Actually I was surprised that changing FREQ_OFFSET value did not make a "linear change" of the sound.  When changing the OPL core frequency, the sound changes linearly and periodically, while only 49716Hz making the sound totally normal.

**Comment by PalMusicFan** [comment] 2018-11-02 02:00
In my test, values much below 100 made the sound right channel sound off-key (an elevated tone),  and an extremely high value (like "1024") made the surround effect difficult to notice, but "384" was acceptable.

**Comment by Malvineous** [comment] 2018-11-06 23:33
`FREQ_OFFSET` is unrelated to the OPL core frequency.  It is the amount that the note pitch is increased by, and the higher the note, the bigger the increase.  This is because musically as notes increase in pitch, the frequency of the notes increases in larger amounts (e.g. C4 -> D4 is a change of 32 Hz, but C8 -> D8 is a change of 512 Hz).  If the offset was constant then the effect would be less noticeable with higher pitched notes, so the offset amount increases with note pitch.

The actual pitch change is an increase of `note / FREQ_OFFSET`, so for a 440 Hz note, the second channel will be `440 + 440 / 128` or 443.43 Hz.  If you change the `FREQ_OFFSET` to 384 then the 440 Hz note will end up as 441.14 Hz, so the effect will be reduced as you have experienced.

Please excuse my mistake in my last reply as I had these numbers backwards, I had forgotten that it was decreasing the numbers that increased the effect of the notes.  A value of `128` was about as low as I could go to maximise the effect without creating off-pitch effects.  Extending this to `384` will reduce the effect so that it is not as strong.

**Comment by Malvineous** [comment] 2018-11-07 00:03
I've finally had a chance to listen to the song and what I think is happening is that it's not distortion, it's that some OPL instruments change their sound based on their pitch.  So as the note pitch changes, other characteristics of the sound change as well.  I have encountered this before with a song from Kiloblaster, which had to be pitch perfect in order for one of the percussion instruments to sound correct.

I think this is one of those cases, and by transposing the note slightly, the resulting instrument also changes.  By increasing the `FREQ_OFFSET` you are essentially disabling the surround effect (or greatly reducing it) so my argument is that you may as well listen in mono/stereo instead if the surround effect is being reduced so low.

Unfortunately I'm not aware of a solution to this, because we are using the OPL chip itself to generate the second channel which has limitations like this.  If we used some other way of performing the transposition then it would likely solve the problem, however all those methods are very CPU hungry.

I'm going to close this issue because it's not a bug in AdPlug as such, it's a limitation of the way we are using the OPL chip to do transposition.  Feel free to continue the discussion even though the issue is closed, I am not closing it to silence the discussion :)

Because of this I do not think it is worth allowing the `FREQ_OFFSET` to be changed (may as well just switch back to stereo) however like I said before, if someone else is willing to add this feature then I have no problem merging the code in.

Either way thank you for bringing it to my attention, and thanks for the short sample song as this is very useful.  I will certainly revisit this if I have any ideas for possible solutions in the future.

**Closed by Malvineous** 2018-11-07 00:03 UTC
Labels: bug

**Comment by PalMusicFan** [comment] 2018-11-07 02:39
Thanks for your reply! 
Yes, you are right! I extracted the INS definition data form the original music file, and finally I found that this instrument was so special. This instrument sounds in this kind only in #C and #G of the highest four octaves (the sound in the clip is  #C of the second highest octave).

**Comment by Malvineous** [comment] 2018-11-07 04:52
Very interesting!  Thanks for confirming, good to know.

**Comment by PalMusicFan** [comment] 2019-01-08 10:20
Hello! 

I have added the feature of user configurable freq offset.  Would you please take a look at it?
https://github.com/PalMusicFan/adplug/tree/user-configurable-freq-offset
https://github.com/PalMusicFan/adplay-unix/tree/user-configurable-freq-offset

I have added a new parameter of "--offset" (or "-w") to adplay-unix and the default value is 128.  In the adplug lib, the default frequency offset value is still defined by FREQ_OFFSET. 

May I send a pull request now?

Thanks so much!
