### ISSUE TITLE
update winamp plugin to latest adplug

### ISSUE THREAD

**Issue by winamp-girl** [adplug/adplug#215] opened 2024-05-31 22:17 UTC
Hi

Is it possible to update the winamp plugin to use latest Adplug?
The latest version was in the year 2017

https://github.com/adplug/winamp/releases/tag/winamp-1.8.2

Download latest winamp (5.9.2) at the bottom of this page

https://about.winamp.com/press/article/winamp-open-source-code

**Comment by binarymaster** [comment] 2024-05-31 23:08
Duplicate of https://github.com/adplug/winamp/issues/25.

**Closed by binarymaster** 2024-05-31 23:08 UTC
