### ISSUE TITLE
Endless loops/event stops in some .dro Dosbox rips.

### ISSUE THREAD

**Issue by Corak667** [adplug/adplug#49] opened 2017-03-24 07:41 UTC
Recorded FM (OPL2) music from game Reunion with latest Dosbox (dro v2 format):
http://coraksoft1.narod.ru/midi/Games/0imf_wlf_dro/Reunion.zip
In track 1 (track1_bad) - it goes to endless loop (freezes the events) at 1:04. 
Also I converted this droV2 to droV1 (with conversion utility from DroTrimmer), and resulting file worked perfectly without event stops on the old release version of AdPlug (2010), but when updated to latest Adplug (2016x) - it hangs the same place as droV2.
Please fix latest Adplug to ignore this event if it's something unlistenable.

**Comment by binarymaster** [comment] 2017-03-24 07:54
Bug confirmed on latest build.

**Comment by Malvineous** [comment] 2017-03-24 23:41
Before this bug is fixed - once the problem is discovered - can we add another .dro test file to reproduce this issue and make the tests fail?  Just so we will be alerted if it ever comes up again.

**Comment by Malvineous** [comment] 2017-03-25 00:32
Had a quick look at this.  The problem seems to be the long delay between the first two songs in the file.  They are just the right length that triggers a bug.

The bug is in the playback code, which is in everything that uses AdPlug (but not AdPlug itself.)  So I have committed [1448d320](https://github.com/adplug/adplay-unix/commit/1448d320989a49ac2746f98f0accecdfd8e0b0f7) for `adplay-unix` and this same fix will have to be applied to `adplay-dos` and `winamp` as well.

@binarymaster Are you able to help out with that, particularly the Winamp one?  It's not so easy for me to compile on my Linux machines.

**Comment by binarymaster** [comment] 2017-03-25 12:32
> Are you able to help out with that, particularly the Winamp one?

Of course, I'll take a look at this.

**Comment by binarymaster** [comment] 2017-03-25 13:34
Fix for Winamp plugin was commited in https://github.com/adplug/winamp/commit/aba893efaf94ed140dfd1367ea46f6cb183fdf8d.

`adplay-dos` is not affected by this issue.

**Comment by binarymaster** [comment] 2017-03-25 23:13
@Corak667 check whether your issue is solved in latest CI build:
https://github.com/adplug/winamp/releases/tag/ci

**Comment by Corak667** [comment] 2017-03-26 00:45
@binarymaster @Malvineous Thank You!
Tested, it solved in latest CI build.

**Closed** 2017-03-26 08:53 UTC
Labels: bug
