### ISSUE TITLE
The "clicks" mentioned in #54 could be removed now

### ISSUE THREAD

**Issue by PalMusicFan** [adplug/adplug#84] opened 2019-06-06 05:00 UTC
Although there are still some imperfections for certain voices, the "clicks" mentioned in #54 could be removed now, at least in the woodyopl. 

Yes, as @nukeykt mentioned, the "clicks" is caused by the phase reset of key on event. 

I did a test in the woodyopl. 

Please look at the function of 
enable_operator(Bitu regbase, op_type* op_pt, Bit32u act_type) 

The phase reset is here: 
`op_pt->tcount = wavestart[wave_sel[wselbase]]*FIXEDPT;`

I added a new state of act_type, OP_ACT_NORESET. 

In woodyopl.h: 
`#define OP_ACT_NORESET 0x03`
In woodyopl.cpp: 
`
if (act_type != OP_ACT_NORESET) {
    op_pt->tcount = wavestart[wave_sel[wselbase]]*FIXEDPT;
}
`
In the case ARC_KON_BNUM of adlib_write(Bitu idx, Bit8u val), all the enable operator actions of regular 0xb0-0xb8 should use OP_ACT_NORESET instead of OP_ACT_NORMAL. 

The act_type OP_ACT_NORESET should be there for all the melody channels, not percussions, since the sound of kick drum may be a bit strange without a phase reset. 

After the modification above, I got phase continuous waves. Yes, some "clicks" were removed, but there appeared new "clicks"! What was up? 

After checking the waveforms, I knew what the problem was. 
If there is phase reset for every key on event, a note always start at the beginning of its wave form, which is always at the zero point. But now, without phase reset, it is not necessarily. So, if the state of the enevlope amplifier suddenly changes greatly, a “click” could also appear though the phase of the original wave is still continous. 

We know the A of envelope could be 15 to 0. Higher value comes with faster attack. 15 means immediately. This could cause the sudden change of the output. 

So I made a limitation, the A of 15 should be changed to a lower value such as 13. 

At case ARC_ATTR_DECR and case ARC_ATTR_DECR+0x10: 
`
if  ((val>>4) >=15) {
    adlibreg[idx] = 208 | (val&15);  //1101 is 13, 11010000 is 208. 
}
`

OK, It worked! Note that the envelope amp is not necessarily start at level 0. The start point was affected by the previous amp level. The attack of 13 is very very short, so I think changing 15 to 13 does not cause any noticeable change in voice. 

The performance is pretty good although certain voices in certain tracks sound a bit different. The most obvious difference I found appears at certain kick drum voices in the melody channels. I have no idea how to identify such kind of voices form normal melody voices.  @Malvineous

I have tested the track @thecoreyburton mentioned. I think it was perfect. I think all the clicks of this track was removed.

**Comment by Malvineous** [comment] 2019-08-07 02:37
Not sure that you can easily identify drums in melodic channels.

Are you sure the clicks are caused by the phase reset on the key-on event?  If the key on normally starts at level 0 then there should be no clicks because of this.

Could it be caused by a sudden jump to level 0 during a key off event instead?

**Comment by PalMusicFan** [comment] 2019-08-09 14:40
I think so, because lots of the "clicks" appear on the voices with long release. So I don't think it is a result of a sudden voice amp level off. 
I have observed the wave form of the "clicks" appear between conecutive notes. The result of my experiment showed that if there is no phase reset (and A of envelope is always <=13 ), most (if not all) of the "clicks" will be removed. 
I will test the shortest release later to see whether it causes a sudden jump to level 0. Thanks!

**Comment by PalMusicFan** [comment] 2019-08-15 09:25
As a test result of opl3_bank_editor (using Nuked OPL3), a key off event could also cause a “click”. 
I guess the R of 15 should also be changed to a lower value such as 13.

**Comment by Malvineous** [comment] 2020-05-11 11:29
I'm going to close this one as WONTFIX also, because in my opinion this is an emulator issue rather than an AdPlug issue.  If you would like to pursue a fix, I recommend getting one of the OPL emulators (Nuked, DOSBox, etc.) updated to include the fix, then letting us know.  We will then update our copy of the emulator from the upstream project in order to pick up the fix.

**Closed by Malvineous** 2020-05-11 11:29 UTC
Labels: question, wontfix
