### ISSUE TITLE
Update to 2.3.2 breaks adplug/adplay-unix, wrong latest version on website

### ISSUE THREAD

**Issue by ehaupt** [adplug/adplug#112] opened 2020-05-17 05:39 UTC
The update to 2.3.2 breaks [adplug/adplay-unix](https://github.com/adplug/adplay-unix) see [build log](https://github.com/adplug/adplug/files/4639712/adplay.txt).

The [website](https://adplug.github.io/) still shows:

```
Newest releases:
Core library 2.3.1
```

**Comment by ehaupt** [comment] 2020-05-23 18:39
Quick fix: https://github.com/freebsd/freebsd-ports/blob/master/audio/adplay/files/patch-configure.ac

**Comment by Malvineous** [comment] 2020-05-24 04:49
I can't reproduce the issue - can you confirm you get the same problem when compiling the git version of adplay?  I think there is a fix in there already so I will do another release of adplay to get it working.

**Comment by Malvineous** [comment] 2020-05-24 05:02
Closing as adplay-unix v1.8.1 should fix the issue.  Please reopen if you still have problems.

**Closed by Malvineous** 2020-05-24 05:02 UTC

**Comment by ehaupt** [comment] 2020-05-24 08:43
Thank you @Malvineous. I can confirm that v1.8.1 solves the issue.
